//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourYears.Areas.JobArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerCompany
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAdress { get; set; }
        public string EmployerName { get; set; }
        public string EmployerPhone { get; set; }
        public string EmployerMail { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string CompanyUserID { get; set; }
        public byte[] Image { get; set; }
        public string ImageWebSite { get; set; }
    }
}
