//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourYears.Areas.JobArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobID { get; set; }
        public string JobName { get; set; }
        public int CompanyID { get; set; }
        public System.DateTime JobStartTime { get; set; }
        public int TimeID { get; set; }
        public decimal PayPerHour { get; set; }
        public string Description { get; set; }
        public string Workplace { get; set; }
        public byte[] Image { get; set; }
        public string ImageWebSite { get; set; }
    }
}
