//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourYears.Areas.BookStoreAreas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookItemCommet
    {
        public int BookCommetID { get; set; }
        public string CustomerName { get; set; }
        public string BookCommet1 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> BookID { get; set; }
        public string CustomerNickName { get; set; }
    }
}
