//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourYears.Areas.BookStoreAreas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public string BookName { get; set; }
        public int SubCategoryID { get; set; }
        public int AuthorID { get; set; }
        public int PublisherID { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Language { get; set; }
        public decimal ListPrice { get; set; }
        public decimal SalePrice { get; set; }
        public string BookDescription { get; set; }
        public string AuthorDescription { get; set; }
        public string OtherImformation { get; set; }
        public Nullable<System.DateTime> OnShelfDate { get; set; }
        public string Image1 { get; set; }
        public byte[] BytesImage1 { get; set; }
        public string Image2 { get; set; }
        public byte[] BytesImage2 { get; set; }
        public string Image3 { get; set; }
        public byte[] BytesImage3 { get; set; }
        public int MainCategoryID { get; set; }
    }
}
