//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourYears.Areas.BookStoreAreas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Customer
    {
        public int CustomerID { get; set; }
        [DisplayName("姓名")]
        public string FullName { get; set; }
        public string NickName { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public string IdentityCard { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Address { get; set; }
    }
}
