//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourYears.Areas.FoodMapArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ShopID { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Image1 { get; set; }
        public byte[] BytesImage1 { get; set; }
        public string Description { get; set; }
        public string Cost { get; set; }
        public string BusinessTime { get; set; }
        public string ShopName { get; set; }
        public Nullable<int> FoodCategoryID { get; set; }
        public string Image2 { get; set; }
        public byte[] BytesImage2 { get; set; }
        public string Image3 { get; set; }
        public byte[] BytesImage3 { get; set; }
        public string ShopLink { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
